
fgms_partner_store_install:
    path: /install
    defaults:
        _controller: FgmsPartnerStoreBundle:Install:install

fgms_partner_store_auth:
    path: /auth
    defaults:
        _controller: FgmsPartnerStoreBundle:Install:auth

fgms_partner_store_homepage:
    path: /
    defaults:
        _controller: FgmsPartnerStoreBundle:Default:home

fgms_partner_store_edit:
    path: /edit/{id}
    defaults:
        _controller: FgmsPartnerStoreBundle:Default:adminStoreEdit
    requirements:
        id: "\\d+"
        
fgms_partner_store_public:
    path: /edit/{permalink}
    defaults:
        _controller: FgmsPartnerStoreBundle:Default:proxyStoreViewAction