<?php

namespace Fgms\PartnerStoreBundle\Repository;

/**
 * AnnouncementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementsRepository extends \Doctrine\ORM\EntityRepository
{
}
